export const INTENTS = [
  "FIRMWARE_UPDATE_REQUEST",
  "FIRMWARE_ACCESS_ISSUE",
  "DOCS_VIDEO_MISMATCH",
  "INSTALL_GUIDANCE",
  "ORDER_STATUS",
  "ORDER_CHANGE_REQUEST",
  "MISSING_DAMAGED_ITEM",
  "WRONG_ITEM_RECEIVED",
  "FUNCTIONALITY_BUG",
  "COMPATIBILITY_QUESTION",
  "PART_IDENTIFICATION",
  "RETURN_REFUND_REQUEST",
  "CHARGEBACK_THREAT",
  "LEGAL_SAFETY_RISK",
  "THANK_YOU_CLOSE",
  "FOLLOW_UP_NO_NEW_INFO",
  "UNKNOWN",
] as const;

export type Intent = (typeof INTENTS)[number];
