/**
 * Intervention Detector
 *
 * Detects when a human (Rob) takes over handling a thread.
 * Intervention signals include:
 * - Direct email from support@ that wasn't auto-generated
 * - Email from rob@ that CCs support@
 * - Manual HubSpot ticket update by Rob
 */

import type { GmailMessage } from "@/lib/import/gmail/fetcher";
import type { InterventionSignal, InterventionChannel } from "./types";

const SUPPORT_EMAIL = "support@squarewheelsauto.com";
const ROB_EMAIL = "rob@squarewheelsauto.com";

/**
 * Check if a Gmail message indicates human intervention
 *
 * Intervention occurs when:
 * 1. An outgoing message from support@ that wasn't drafted by Lina
 * 2. A message from rob@ that CCs support@
 */
export function detectGmailIntervention(
  message: GmailMessage & { cc?: string[] },
  threadId: string,
  gmailThreadId: string,
  wasGeneratedByAgent: boolean
): InterventionSignal | null {
  const fromEmail = extractEmail(message.from);
  const toEmails = message.to.map(extractEmail);
  const ccEmails = message.cc?.map(extractEmail) || [];

  // Case 1: Outgoing from support@ that wasn't auto-generated
  if (fromEmail === SUPPORT_EMAIL && !message.isIncoming && !wasGeneratedByAgent) {
    return {
      type: "direct_email",
      threadId,
      gmailThreadId,
      handler: ROB_EMAIL, // Rob sending from support@
      channel: "email",
      timestamp: message.date,
      content: message.body,
    };
  }

  // Case 2: Rob emails customer and CCs support@
  if (fromEmail === ROB_EMAIL) {
    const ccSupport = ccEmails.includes(SUPPORT_EMAIL) || toEmails.includes(SUPPORT_EMAIL);
    if (ccSupport) {
      return {
        type: "cc_support",
        threadId,
        gmailThreadId,
        handler: ROB_EMAIL,
        channel: "email",
        timestamp: message.date,
        content: message.body,
      };
    }
  }

  return null;
}

/**
 * Check if a HubSpot activity indicates human intervention
 *
 * Rob owns the HubSpot tickets when escalated, so any manual activity
 * (notes, status changes, manual emails) from him indicates intervention.
 */
export function detectHubSpotIntervention(
  activity: {
    type: "note" | "email" | "status_change";
    actorEmail?: string;
    content?: string;
    timestamp: Date;
  },
  threadId: string,
  hubspotTicketId: string
): InterventionSignal | null {
  // Only Rob's actions count as intervention
  if (activity.actorEmail !== ROB_EMAIL) {
    return null;
  }

  // Any action from Rob is an intervention
  return {
    type: "hubspot_update",
    threadId,
    hubspotTicketId,
    handler: ROB_EMAIL,
    channel: "hubspot",
    timestamp: activity.timestamp,
    content: activity.content,
  };
}

/**
 * Check if intervention is from admin UI (manual takeover)
 */
export function detectAdminIntervention(
  handler: string,
  threadId: string
): InterventionSignal {
  return {
    type: "admin_takeover",
    threadId,
    handler,
    channel: "admin_ui",
    timestamp: new Date(),
  };
}

/**
 * Check if a thread is currently in human handling mode
 */
export async function isThreadBeingHandled(
  supabase: typeof import("@/lib/db").supabase,
  threadId: string
): Promise<boolean> {
  const { data } = await supabase
    .from("threads")
    .select("human_handling_mode")
    .eq("id", threadId)
    .single();

  return data?.human_handling_mode === true;
}

/**
 * Check if an outgoing message was generated by the agent
 * by looking for the message in our drafts table
 */
export async function wasMessageGeneratedByAgent(
  supabase: typeof import("@/lib/db").supabase,
  gmailMessageId: string
): Promise<boolean> {
  // Check if we have a draft or sent message record with this Gmail ID
  const { data } = await supabase
    .from("messages")
    .select("id")
    .eq("channel_metadata->>sent_gmail_message_id", gmailMessageId)
    .maybeSingle();

  return !!data;
}

/**
 * Extract email address from "Name <email@example.com>" format
 */
function extractEmail(emailString: string): string {
  const match = emailString.match(/<([^>]+)>/);
  if (match) {
    return match[1].toLowerCase();
  }
  return emailString.toLowerCase().trim();
}

/**
 * Get the handler email from a thread that's in human handling mode
 */
export async function getThreadHandler(
  supabase: typeof import("@/lib/db").supabase,
  threadId: string
): Promise<string | null> {
  const { data } = await supabase
    .from("threads")
    .select("human_handler")
    .eq("id", threadId)
    .single();

  return data?.human_handler || null;
}
