-- Add role column to messages table for distinguishing drafts from sent messages
-- This column allows us to track:
-- - 'draft': Generated by Lina, awaiting approval
-- - 'sent': Approved and sent to customer
-- - 'internal': Internal notes (not sent to customer)
-- - NULL: Regular customer/outbound messages

ALTER TABLE messages ADD COLUMN IF NOT EXISTS role TEXT;

-- Create index for filtering drafts efficiently
CREATE INDEX IF NOT EXISTS idx_messages_role ON messages(role) WHERE role IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN messages.role IS 'Message role: draft, sent, internal, or null for regular messages';
